// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2q5t9M9x9_HjQbH51nKciOv3zkKDmVyg',
    appId: '1:1090306874807:android:db9ff121852e23e4d85c32',
    messagingSenderId: '1090306874807',
    projectId: 'solo-leveling-4ab30',
    databaseURL: 'https://solo-leveling-4ab30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solo-leveling-4ab30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2AURFe-jqYZvSuWSV5khv_OMfA-NX1k',
    appId: '1:1090306874807:ios:4ce0f4af8581d780d85c32',
    messagingSenderId: '1090306874807',
    projectId: 'solo-leveling-4ab30',
    databaseURL: 'https://solo-leveling-4ab30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solo-leveling-4ab30.firebasestorage.app',
    iosBundleId: 'com.example.soloLeveling',
  );
}
